spring:
  application:
    name: craft-issue
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/craft?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  redis:
    host: 116.62.114.28
    port: 6379
    jedis:
      pool:
        max-active: 2000
        max-wait: 5000
        max-idle: 500
        min-idle: 0
    timeout: 5000
  servlet:
    multipart:
      max-file-size:  300MB
      max-request-size: 300MB


mybatis:
  type-aliases-package: com/zkwp/issue
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8004
  servlet:
    context-path: /craft/issue


eureka:
  client:  #客户端注册进eureka
    service-url:
      defaultZone: http://eureka.zkwp.com:7001/eureka/
  instance:
    instance-id: issue
    prefer-ip-address: true




