server:
  port: 7001

eureka:
  instance:
    hostname: eureka.zkwp.com  #eureka 服务端的实例名
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      #设置与Eureka Server 交互的地址查询服务和注册服务



spring:
  application:
    name: craft-eureka
